services:
    phlexible_element_finder.filter_manager:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Filter\FilterManager
        arguments: [[]]

    phlexible_element_finder.treenode_matcher:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Matcher\TreeNodeMatcher
        arguments:
            - "@phlexible_tree.tree_manager"
            - "@phlexible_element.element_service"
            - "@phlexible_element.element_history_manager"
            - "%phlexible_element_finder.use_master_language_as_fallback%"

    phlexible_element_finder.finder:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\ElementFinder
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@event_dispatcher"
            - "@phlexible_element_finder.treenode_matcher"
            - "@phlexible_element_finder.filter_manager"
            - "@phlexible_element_finder.cache"
            - false

    phlexible_element_finder.file_cache:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Cache\FileCache
        arguments:
            - "@phlexible_element_finder.filter_manager"
            - "@phlexible_element_finder.invalidator"
            - "%phlexible_element_finder.cache_dir%"

    phlexible_element_finder.always_invalidate_invalidator:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Invalidator\AlwaysInvalidateInvalidator

    phlexible_element_finder.ttl_invalidator:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Invalidator\TtlInvalidator
        arguments:
            - "%phlexible_element_finder.invalidator_ttl%"

    phlexible_element_finder.timestamp_invalidator:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Invalidator\TimestampInvalidator
        arguments:
            - "@properties"

    phlexible_element_finder.lookup_builder:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Lookup\LookupBuilder
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@phlexible_element.element_service"
            - "@phlexible_element.element_meta_set_resolver"
            - "@phlexible_element.element_meta_data_manager"
            - "@event_dispatcher"

    # comands
    phlexible_element_finder.build_command:
        class: Phlexible\Bundle\ElementFinderBundle\Command\BuildCommand
        arguments:
            - "@phlexible_tree.tree_manager"
            - "@phlexible_element_finder.lookup_builder"
        tags:
            - {name: console.command}

    phlexible_element_finder.find_command:
        class: Phlexible\Bundle\ElementFinderBundle\Command\FindCommand
        arguments:
            - "@phlexible_element_finder.finder"
        tags:
            - {name: console.command}

    # data collectors
    phlexible_element_finder.data_collector:
        class: Phlexible\Bundle\ElementFinderBundle\DataCollector\ElementFinderDataCollector
        arguments:
            - "@phlexible_element_finder.finder"
        tags:
            - {name: data_collector, template: "@PhlexibleElementFinder/Collector/result_pools.html.twig", id: element_finder, priority: -1}

    # event listeners
    phlexible_element_finder.node_listener:
        class: Phlexible\Bundle\ElementFinderBundle\EventListener\NodeListener
        arguments:
            - "@phlexible_element_finder.lookup_builder"
            - "@properties"
        tags:
            - {name: kernel.event_subscriber}

    # fields
    phlexible_element_finder.field.finder:
        class: Phlexible\Bundle\ElementFinderBundle\Field\FinderField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: finder}

    # role providers
    phlexible_element_finder.role_provider:
        class: Phlexible\Bundle\ElementFinderBundle\RoleProvider\ElementFinderRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
