services:
    phlexible_element_finder.filter_manager:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Filter\FilterManager
        arguments: [[]]

    phlexible_element_finder.treenode_matcher:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\Matcher\TreeNodeMatcher
        arguments:
            - @phlexible_tree.tree_manager
            - @phlexible_element.element_service
            - @phlexible_element.element_history_manager
            - %phlexible_element_finder.use_master_language_as_fallback%

    phlexible_element_finder.finder:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\ElementFinder
        arguments:
            - @doctrine.dbal.default_connection
            - @event_dispatcher
            - @phlexible_element_finder.treenode_matcher
            - @phlexible_element_finder.filter_manager
            - %phlexible_element_finder.cache_dir%
            - false

    phlexible_element_finder.lookup_builder:
        class: Phlexible\Bundle\ElementFinderBundle\ElementFinder\LookupBuilder
        arguments:
            - @doctrine.orm.entity_manager
            - @phlexible_element.element_service
            - @phlexible_element.element_meta_set_resolver
            - @phlexible_element.element_meta_data_manager
            - @event_dispatcher

    # asset providers
    phlexible_element_finder.asset_provider:
        class: Phlexible\Bundle\ElementFinderBundle\AssetProvider\ElementFinderAssetProvider
        public: false
        tags:
            - {name: phlexible_gui.asset_provider, priority: 100}

    # event listeners
    phlexible_element_finder.listener.publish_node:
        class: Phlexible\Bundle\ElementFinderBundle\EventListener\NodeListener
        arguments: [@phlexible_element_finder.lookup_builder]
        tags:
            - {name: kernel.event_subscriber}

    # fields
    phlexible_element_finder.field.finder:
        class: Phlexible\Bundle\ElementFinderBundle\Field\FinderField
        public: false
        tags:
            - {name: phlexible_elementtype.field, alias: finder}

    # role providers
    phlexible_element_finder.role_provider:
        class: Phlexible\Bundle\ElementFinderBundle\RoleProvider\ElementFinderRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
